---
apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZnZzd3FvMjMK
  CLOUDINARY_KEY: MTUxNjU4NzExMjUxMzY5Cg==
  CLOUDINARY_SECRET: NEhSZTlPWnozdXF5dUZlcUtZaGFXTDFVRXp3Cg==
  MAPBOX_TOKEN: cGsuZXlKMUlqb2lZVzVwYTJWMGQyRnJaV3RoY2lJc0ltRWlPaUpqYlhNM00zcDFZemN3WVRKak1u
ZHlPSEJ5YVRSMWFuTjJJbjAuakxTTEZjOS1xMnh1TTVUMVFSNy1uQQo=
  DB_URL: bW9uZ29kYitzcnY6Ly9hbmlrZXR3YWtla2FyMjRfZGJfdXNlcjptYlFRYUhvWmlaQUtKdWZTQGFu
aWtldC1kYi55eHhzeWxrLm1vbmdvZGIubmV0Lz9hcHBOYW1lPUFuaWtldC1EQgo=
  SECRET: ZGV2b3Bzc2hhY2sK

---
